version: '3'
services:
  crawler:
    build: .
    environment:
      - USERNAME=root
      - PASSWORD=root
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: tutum/mongodb:3.2
    environment:
      MONGODB_USER: root
      MONGODB_PASS: root
      MONGODB_DATABASE: bf-notifier