version: '3'
services:
  crawler:
    build: .
    environment:
      - USERNAME=root
      - PASSWORD=root
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongodb:4.2.0
    volumes:
    - /data/db:/data/db
    ports:
    - "27017:27017"
    environment:
      MONGODB_USER: root
      MONGODB_PASS: root
      MONGODB_DATABASE: bf-notifier