# Default values for sms-outbound.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: gcr.io/zens-main/bfNotifier
  tag: latest
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 200m
    memory: 128Mi
env: