# Default values for sms-outbound.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: gcr.io/zens-main/bf-notifier
  tag: latest
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 200m
    memory: 128Mi
seedResources:
  limits:
    cpu: 1000m
    memory: 2048Mi
  requests:
    cpu: 1000m
    memory: 2048Mi
env:
  username: root
  url: dev-play-mongodb-mongodb